[workspace]
resolver = "2"
members = [
  "mc-lsp",
  "mc-analysis",
  "mc-source",
  "mc-test",
]

[workspace.dependencies]
mc-source = { path = "mc-source" }
mc-analysis = { path = "mc-analysis" }
mc-test = { path = "mc-test" }
