[package]
name = "mc-source"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
la-arena = "0.3.1"
salsa = "0.17.0-pre.2"
url = "2.5.0"
